config/routes.rb
Rails.application.routes.draw do
   devise_for :customers

   devise_for :admins, controllers: {
    sessions:      'admins/devise/sessions',
    passwords:     'admins/devise/passwords',
    registrations: 'admins/devise/registrations'
  }
 #↑controllersでカスタマー側とURLを分けてます。

 # customer側ルーティング
  root "products#top"
  get "products/about" => "products#about", as: 'products_about'
  patch "customers/usubscribe" => "customers#usubscribe", as: 'customers_usubscribe'
  get "customers/withdraw" => "customers#withdraw", as: 'customers_withdraw'
  resources :products, only: [:index, :show]
  resources :customers, only: [:edit ,:update, :show]
  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  get "orders/thanks" => "orders#thanks", as: 'orders_thanks'
  post 'orders/comfirm' => 'orders#comfirm', as: 'order_comfirm'
  get "orders/comfirm" => "orders#comfirm", as: 'orders_comfirm'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only:[:show, :new, :create, :index]
  get "search" => "products#search", as:"customers_search"
  # admin側ルーティング
  namespace :admins do
    root "devise#new"
    get "top" => "homes#top", as: 'home'
    resources :products, only: [:new, :show, :index, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_datails, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:index, :show, :update]
    get "search" => "products#search", as:"search"
  end
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy


  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :first_name_kana, presence: true, format: {with: /\A[ァ-ヶー－]+\z/}
  validates :tel, presence: true, format: {with: /\A\d{10,11}\z/}, numericality: true
  validates :zipcode, presence: true, format: {with: /\A\d{7}\z/}, numericality: true
  validates :address, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true


   def active_for_authentication?
    super && (self.customer_status == true)
  end

  def self.search(search, model)
    if model == "customer"
      Customer.where('first_name_kana LIKE ? OR last_name_kana LIKE ? OR first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
    else
      Customer.all
    end
  end

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
     redirect_to admins_customer_path(@customer)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :zipcode, :address, :tel, :customer_status)
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to customer_path(current_customer.id), notice: "登録情報を編集しました"
    else
       flash[:warning] = "入力内容が間違ってるよ"
       render :edit
    end
  end

  def show
    @customer = Customer.find(params[:id])

  end

  def withdraw

  end

  def usubscribe
      @customer = Customer.find(current_customer.id)
      if @customer.update!(customer_status: false)
         sign_out current_customer
      end
      redirect_to root_path
  end


  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :zipcode, :address, :tel)
  end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">

  <h4 class="Menu">登録情報編集</h4>
  <%= form_for(@customer) do |f| %>
  <div class="row">
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="col-md-2"><%= f.label :名前 %></div>
    <div class="col-md-1"><%= f.label :姓 %></div>
    <div class="col-md-4"><%= f.text_field :last_name %></div>
    <div class="col-md-1"><%= f.label :名 %></div>
    <div class="col-md-4"><%= f.text_field :first_name %></div>
  </div><br>

  <div class="row">
    <div class="col-md-2"><%= f.label :フリガナ %></div>
    <div class="col-md-1"><%= f.label :セイ %></div>
    <div class="col-md-4"><%= f.text_field :last_name_kana %></div>
    <div class="col-md-1"><%= f.label :メイ %></div>
    <div class="col-md-4"><%= f.text_field :first_name_kana %></div>
  </div><br>

  <div class="row">
    <div class="col-md-3"><%= f.label :メールアドレス %></div>
    <div class="col-md-9"><%= f.text_field :email %></div>
    <div class="col"></div>
  </div><br>

  <div class="row">
    <div class="col-md-3"><%= f.label :郵便番号（ハイフンなし） %></div>
    <div class="col-md-9"><%= f.text_field :zipcode %></div>
    <div class="col"></div>
  </div><br>

  <div class="row">
    <div class="col-md-3"><%= f.label :住所 %></div>
    <div class="col-md-9"><%= f.text_field :address, :size=>"40x10" %></div>
    <div class="col"></div>
  </div><br>

  <div class="row">
    <div class="col-md-3"><%= f.label :電話番号（ハイフンなし） %></div>
    <div class="col-md-9"><%= f.text_field :tel %></div>
    <div class="col"></div>
  </div><br>
    <%= f.submit "変更を保存する", class: "btn btn-primary" %>
  <% end %>
    <%= link_to "退会する", customers_withdraw_path, class: "btn btn-danger" %>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12">
		<h2 class="Menu">MYPAGE</h2>
			<main>
				<table class="table customer-show">
						<tr class="brown-border">
							<td class="active">氏名</td>
							<td>
								<%= @customer.last_name %>
								<%= @customer.first_name %>
							</td>
						</tr>
						<tr class="brown-border">
							<td class="active">カナ</td>
							<td>
								<%= @customer.last_name_kana %>
								<%= @customer.first_name_kana %>
							</td>
						</tr>
						<tr class="brown-border">
							<td class="active">郵便番号</td>
							<td><%= @customer.zipcode %></td>
						</tr>
						<tr class="brown-border">
							<td class="active">住所</td>
							<td><%= @customer.address %></td>
						</tr>
						<tr class="brown-border">
							<td class="active">電話番号</td>
							<td><%= @customer.tel %></td>
						</tr>
						<tr class="brown-border">
							<td class="active">メールアドレス</td>
							<td><%= @customer.email %></td>
						</tr>
				</table>
			</main>
	</div>
  </div>


			<div class="offset-sm-1 col-sm-3">
				<div class="row">
					<p>配送先</p>
					<p><%= link_to "一覧を見る", addresses_path, class: "btn btn-default" %></p>
				</div>
				<div class="row">
					<p>注文一覧</p>
					<p><%= link_to "一覧を見る", orders_path, class: "btn btn-default" %></p>
				</div>
			</div>
			<div>
				<table align="right">
					<tbody>
						<tr>
							<td><%= link_to  "編集する", edit_customer_path(@customer), class: "btn btn-success" %></td>
							<td><%= link_to "パスワードを変更する", edit_customer_registration_path, class: "btn btn-primary" %></td>
						</tr>
					</tbody>
				</table>
			</div>
</div>

app/views/customers/withdraw.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-12 text-center">
      <h2 class="title">本当に退会しますか？</h2>
      <p>退会すると、会員登録情報や<br>
      これまでの購入履歴が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。<br>
      </p>
      <%= link_to "退会しない",customer_path(current_customer.id), class: "btn btn-primary" %>
      <%= link_to "退会する", customers_usubscribe_path, method: :patch, "data-confirm" => "本当に退会するの？", class: "btn btn-danger" %>
    </div>
  </div>
</div>