config/routes.rb
Rails.application.routes.draw do
   devise_for :customers

   devise_for :admins, controllers: {
    sessions:      'admins/devise/sessions',
    passwords:     'admins/devise/passwords',
    registrations: 'admins/devise/registrations'
  }
 #↑controllersでカスタマー側とURLを分けてます。

 # customer側ルーティング
  root "products#top"
  get "products/about" => "products#about", as: 'products_about'
  patch "customers/usubscribe" => "customers#usubscribe", as: 'customers_usubscribe'
  get "customers/withdraw" => "customers#withdraw", as: 'customers_withdraw'
  resources :products, only: [:index, :show]
  resources :customers, only: [:edit ,:update, :show]
  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  get "orders/thanks" => "orders#thanks", as: 'orders_thanks'
  post 'orders/comfirm' => 'orders#comfirm', as: 'order_comfirm'
  get "orders/comfirm" => "orders#comfirm", as: 'orders_comfirm'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only:[:show, :new, :create, :index]
  get "search" => "products#search", as:"customers_search"
  # admin側ルーティング
  namespace :admins do
    root "devise#new"
    get "top" => "homes#top", as: 'home'
    resources :products, only: [:new, :show, :index, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_datails, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:index, :show, :update]
    get "search" => "products#search", as:"search"
  end
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :orders
  has_many :cart_items
  attachment :image

  with_options presence: true do
    validates :genre_id
    validates :name, length: {maximum: 20, minimum: 1}
    validates :introduction
    validates :price, numericality: true
  end

  validates :status, inclusion: { in: [true, false] }

    TAX = 1.1

    def tax_price
      tax_price = price * TAX
      tax_price.floor
    end

  def self.search(search, model)
    if model == "product"
      Product.where(['name LIKE ?', "%#{search}%"])
    else
      Product.all
    end
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @product = Product.new
    @genres = Genre.where(genre_status: "true" )
  end

  def show
    @product = Product.find(params[:id])
  end

  def index
    @genres = Genre.all
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @products = @genre.products.page(params[:page])
    else
      @products = Product.page(params[:page]).includes(:genre)
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "商品を登録しました。"
      redirect_to admins_product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product =Product.find(params[:id])
    @genres = Genre.where(genre_status: "true" )
  end

  def update
    @product =Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admins_products_path
      flash[:notice] = "商品を更新しました。"
    else
      render :edit
    end
  end

  def search
    @model = params[:model]
    if @model == "customer"
      @customers = Customer.search(params[:search], @model)
    else
      @products = Product.search(params[:search], @model).includes(:genre)
    end
  end

  protected

  def product_params
    params.require(:product).permit(:name, :introduction, :image, :price, :status, :genre_id, :genre_name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_customer!, except: [:index, :top, :about, :show, :search]
  
   def index
    @genres = Genre.where(genre_status: "true" )
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @products = @genre.products.all
    else
      @products = Product.joins(:genre).where("genres.genre_status = ?", true )
    end
  end

  def show
    @genres = Genre.where(genre_status: "true" )
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @products = @genre.products.all.includes(:genre)
    else
      @products = Product.joins(:genre).where("genres.genre_status = ?", true )
    end
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  def about
  end

  def top
    @genres = Genre.where(genre_status: "true" )
    @recommendation = Product.where(status: "true" ).joins(:genre).where("genres.genre_status = ?", true ).limit(4).order(created_at: :desc)
  end

   def search
    @model = "product"
    @products = Product.joins(:genre).where("genres.genre_status = ?", true ).search(params[:search], @model)
  end

  private
    def product_params
      params.require(:product).permit(:genre_id, :name, :introduction, :image, :price, :status)
    end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/_search_box_admin.html.erb
<% if admin_signed_in? %>
  <div class="search-form">
  	<%= form_tag(admins_search_path, :method => "get") do %>
  	  <%= text_field_tag :search, "", class: "search-box" %>
      <%= select_tag :model, options_for_select({商品: :product, お客様: :customer}) %>
	  <%= submit_tag " 検索 ", :name => nil %>
    <% end %>
  </div>
<% end %>

app/views/admins/products/edit.html.erb
<div class = "row admins products_edit_main">
  <h4 class="Menu">商品編集</h4>
  <%= form_for (@product), url: admins_product_path(@product), method: :patch do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class = "col-md-4 admins products_edit_image">
      <%= attachment_image_tag @product, :image, size: "300x300", format: 'jpeg', fallback: "no-data.jpg", size: "300x300" %><br><br>
      <%= f.attachment_field :image %>
    </div>

    <div class="col-md-8 admins products_edit_image_information">
      <h4>商品名</h4>
        <%= f.text_field :name %>
      <h4>商品説明</h4>
        <%= f.text_area :introduction %>
      <h4>ジャンル</h4>
        <%= f.select :genre_id, Genre.all.map {|genre| [genre.genre_name, genre.id ] } %>
      <h4>税抜価格</h4>
        <%= f.text_field :price %> 円
      <h4>販売ステータス</h4>
        <%= f.select :status, {"販売中" => "true", "販売中止"=> "false"} %><br><br>
      <div class="button">
        <%= f.submit '変更を保存' %>
      </div><br>
    </div>
  <% end %>

</div>

app/views/admins/products/index.html.erb
<div class = "row">
    <div class="col-xs-12 admins  products_index_main">
      <h4 class="Menu">商品一覧</h4>
    	<%= link_to new_admins_product_path do %>
          <i class="glyphicon glyphicon-plus-sign icon" style = "font-size: 15px">新商品登録</i>
        <% end %>

    	<table class = "table">
	      <thead>
	    	<tr>
    		  <th class="col-xs-1">商品ID</th>
    		  <th class="col-xs-6">商品名</th>
    		  <th class="col-xs-2">税抜価格</th>
    		  <th class="col-xs-2">ジャンル</th>
    		  <th class="col-xs-1">ステータス</th>
	    	</tr>
	      </thead>
	      <tbody>
	      	<% @products.each do |product| %>
	    	<tr>
    		  <td><%= product.id %></td>
    		  <td><%= link_to product.name, admins_product_path(product) %></td>
    		  <td><%= (product.price).to_s(:delimited) %> 円</td>
    		  <td><%= product.genre.genre_name %></td>
	    	  <td>
	    		<% if product.status? %>
                  販売中
                <% else %>
                  売切れ
                <% end %>
	    	  </td>
	    	</tr>
	      <% end %>
	      </tbody>
    	</table>
    </div>
</div>
<%= paginate @products %>

app/views/admins/products/new.html.erb
<div class = "row admins products_new_main">
<h4 class="Menu">商品新規登録</h4>
  <%= form_for (@product), url: admins_products_path, method: :post do |f| %>
     <%= render 'layouts/error_messages', model: f.object %>
    <div class ="col-md-4 product_image">
      <%= attachment_image_tag @product, :image, size: "300x300", format: 'jpeg', fallback: "no-data.jpg", size: "300x300" %>
      <%= f.attachment_field :image %>
    </div>
    <div class="col-md-8 admins product_new_information">
      <h4>商品名</h4>
        <%= f.text_field :name, :placeholder => "商品名" %>
      <h4>商品説明</h4>
        <%= f.text_area :introduction, :placeholder => "商品説明" %>
      <h4>ジャンル</h4>
        <%= f.select :genre_id, Genre.all.map {|genre| [genre.genre_name, genre.id ] } %>
      <h4>税抜価格</h4>
        <%= f.text_field :price, :placeholder => "300" %> 円
      <h4>販売ステータス</h4>
        <%= f.select :status, { "販売中" => :true, "売切れ"=> :false } %><br><br>
        <%= f.submit '新規登録' %><br><br>
    </div>
  <% end %>
</div>

app/views/admins/products/search.html.erb
<% if @model == "customer" %>
  <% if @customers.present? %>
    <table class="table table-sm customer-index">
    <thead class="thead-light">
  	  <th>会員ID</th>
  	  <th>氏名</th>
  	  <th>メールアドレス</th>
  	  <th>ステータス</th>
    </thead>

    <tbody>
  	  <% @customers.each do |customer| %>
	  <tr>
	  	<td><%= customer.id %></td>
	  	<td><%= link_to customer.last_name.to_s + customer.first_name.to_s, admins_customer_path(customer) %></td>
	  	<td><%= customer.email %></td>
	  	<td>
	  	　<% if customer.customer_status %>
  		    有効会員
  	      <% else %>
  		    無効会員
  	      <% end %>
	  	</td>
	  </tr>
	  <% end %>
	</tbody>
	</table>
  <% else %>
  <h2>customers search for " <%= params[:search] %> "</h2>
	  ・該当のユーザーはいません
  <% end %>
<% elsif @model == "product" %>
  <% if @products.present? %>
    <table class = "table">
      <thead>
    	<tr>
		  <th>商品ID</th>
		  <th>商品名</th>
		  <th>税抜価格</th>
		  <th>ジャンル</th>
		  <th>ステータス</th>
    	</tr>
      </thead>
      <tbody>
      	<% @products.each do |product| %>
    	<tr>
		  <td><%= product.id %></td>
		  <td><%= link_to product.name, admins_product_path(product) %></td>
		  <td><%= (product.price).to_s(:delimited) %> 円</td>
		  <td><%= product.genre.genre_name %></td>
    	  <td>
    		<% if product.status? %>
              販売中
            <% else %>
              売切れ
            <% end %>
    	  </td>
    	</tr>
      	<% end %>
      </tbody>
	</table>
  <% else %>
    <h2>products search for " <%= params[:search] %> "</h2>
      ・該当の商品はありません
    <% end %>
<% end %>

app/views/admins/products/show.html.erb
<div class = "row admins products_show_main">
<h4 class="Menu">商品詳細</h4>

  <div class="col-md-4 admins product_show_image">
    <%= attachment_image_tag @product, :image, size: "300x300", format: 'jpeg', fallback: "no-data.jpg", size: "300x300" %>
  </div>

  <div class="col-md-8 admins product_show_information">
    <div class="row">
      <h4 class="col-md-4">商品名</h4>
        <span class="col-md-8 product_show"><%= @product.name %></span>
    </div>
    <div class="row">
    <h4 class="col-md-4">商品説明</h4>
      <span class="col-md-8 product_show"><%= @product.introduction %></span>
    </div>
    <div class="row">
    <h4 class="col-md-4">ジャンル</h4>
      <span class="col-md-8 product_show"><%= @product.genre.genre_name %></span>
    </div>
    <div class="row">
    <h4 class="col-md-4">税込価格 (税抜価格)</h4>
      <span class="col-md-8 product_show"><%= @product.tax_price.to_s(:delimited) %>(<%= (@product.price).to_s(:delimited) %>) 円</span>
    </div>
    <div class="row">
    <h4 class="col-md-4">販売ステータス</h4>
    <span class="col-md-8 product_show">
      <% if @product.status? %>
        販売中
      <% else %>
        売切れ
      <% end %>
    </span>
    <div>
      <%= link_to "編集", edit_admins_product_path, class: "btn btn-primary" %>
    </div>
  </div>

</div>