config/routes.rb
Rails.application.routes.draw do
   devise_for :customers

   devise_for :admins, controllers: {
    sessions:      'admins/devise/sessions',
    passwords:     'admins/devise/passwords',
    registrations: 'admins/devise/registrations'
  }
 #↑controllersでカスタマー側とURLを分けてます。

 # customer側ルーティング
  root "products#top"
  get "products/about" => "products#about", as: 'products_about'
  patch "customers/usubscribe" => "customers#usubscribe", as: 'customers_usubscribe'
  get "customers/withdraw" => "customers#withdraw", as: 'customers_withdraw'
  resources :products, only: [:index, :show]
  resources :customers, only: [:edit ,:update, :show]
  resources :cart_items, only: [:index, :create, :update, :destroy] do
    collection do
        delete 'destroy_all'
    end
  end
  get "orders/thanks" => "orders#thanks", as: 'orders_thanks'
  post 'orders/comfirm' => 'orders#comfirm', as: 'order_comfirm'
  get "orders/comfirm" => "orders#comfirm", as: 'orders_comfirm'
  resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  resources :orders, only:[:show, :new, :create, :index]
  get "search" => "products#search", as:"customers_search"
  # admin側ルーティング
  namespace :admins do
    root "devise#new"
    get "top" => "homes#top", as: 'home'
    resources :products, only: [:new, :show, :index, :create, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :order_datails, only: [:update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :order_items, only: [:index, :show, :update]
    get "search" => "products#search", as:"search"
  end
   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :genre
  has_many :order_items, dependent: :destroy
  has_many :orders
  has_many :cart_items
  attachment :image

  with_options presence: true do
    validates :genre_id
    validates :name, length: {maximum: 20, minimum: 1}
    validates :introduction
    validates :price, numericality: true
  end

  validates :status, inclusion: { in: [true, false] }

    TAX = 1.1

    def tax_price
      tax_price = price * TAX
      tax_price.floor
    end

  def self.search(search, model)
    if model == "product"
      Product.where(['name LIKE ?', "%#{search}%"])
    else
      Product.all
    end
  end
end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @product = Product.new
    @genres = Genre.where(genre_status: "true" )
  end

  def show
    @product = Product.find(params[:id])
  end

  def index
    @genres = Genre.all
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @products = @genre.products.page(params[:page])
    else
      @products = Product.page(params[:page]).includes(:genre)
    end
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "商品を登録しました。"
      redirect_to admins_product_path(@product)
    else
      render :new
    end
  end

  def edit
    @product =Product.find(params[:id])
    @genres = Genre.where(genre_status: "true" )
  end

  def update
    @product =Product.find(params[:id])
    if @product.update(product_params)
      redirect_to admins_products_path
      flash[:notice] = "商品を更新しました。"
    else
      render :edit
    end
  end

  def search
    @model = params[:model]
    if @model == "customer"
      @customers = Customer.search(params[:search], @model)
    else
      @products = Product.search(params[:search], @model).includes(:genre)
    end
  end

  protected

  def product_params
    params.require(:product).permit(:name, :introduction, :image, :price, :status, :genre_id, :genre_name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_customer!, except: [:index, :top, :about, :show, :search]
  
   def index
    @genres = Genre.where(genre_status: "true" )
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @products = @genre.products.all
    else
      @products = Product.joins(:genre).where("genres.genre_status = ?", true )
    end
  end

  def show
    @genres = Genre.where(genre_status: "true" )
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      @products = @genre.products.all.includes(:genre)
    else
      @products = Product.joins(:genre).where("genres.genre_status = ?", true )
    end
    @product = Product.find(params[:id])
    @cart_item = CartItem.new
  end

  def about
  end

  def top
    @genres = Genre.where(genre_status: "true" )
    @recommendation = Product.where(status: "true" ).joins(:genre).where("genres.genre_status = ?", true ).limit(4).order(created_at: :desc)
  end

   def search
    @model = "product"
    @products = Product.joins(:genre).where("genres.genre_status = ?", true ).search(params[:search], @model)
  end

  private
    def product_params
      params.require(:product).permit(:genre_id, :name, :introduction, :image, :price, :status)
    end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_genres-search.html.erb

<table>
	<thead>
		<tr>
			<th>ジャンル検索</th>
		</tr>
	</thead>
	<tbody>
		<% genres.each do |genre| %>
		<tr>
			<td><%= link_to genre.genre_name, products_path(genre_id: genre) %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/products/_search_box_customer.html.erb
<%= form_tag(customers_search_path, method: :get ) do %>
  <%= text_field_tag :search  %>
  <%= submit_tag " 検索 ", :name => nil %>
<% end %>

app/views/products/about.html.erb
<div class="about">
	<div class="row">
		<div class="col-lg-6">
			<h4 class="title">ABOUT</h4>ながのCakeは全国発送可能なケーキ屋さんです。<br>
			お子様からお年寄りの方までお召し上がりいただけるよう、<br>
			様々なバリエーションをご用意しております。<br>
			また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
			ぜひご注文ください。
        </div>
        <div class="col-lg-6">
            <img class="image" src="https://demo.tcd-theme.com/tcd029/wp-content/uploads/2015/11/41.jpg" alt="" title="" style="max-width: 100%;">
        </div>
    </div>
	<div class="row">
		<div class="col-lg-6">
            <img class="image" src="https://demo.tcd-theme.com/tcd029/wp-content/uploads/2015/11/about03.jpg" alt="" title="" style="max-width: 100%;">
        </div>
		<div class="col-lg-6">
			<h4 class="title">HAPPY</h4>
			スィーツのおいしさと食文化を正しく伝えていきたい、<br>
			フランス菓子を神戸という土地に根付かせたい、<br>という想いでお菓子を作っています。 <br>
			古くから外国の文化や食に親しみ、伝統を守りながらも、<br>
			新しいものを上手に取り入れて今の時代を見つめながらも、<br>
			その時々の動きに流されず、旬のもの、からだにやさしいものを、<br>基本の製法を踏まえて作っていきたいと考えています。
        </div>
    </div>
    <div class="row">
		<div class="col-lg-6">
			<h4 class="title">SWEETY</h4>
			スィーツのおいしさと食文化を正しく伝えていきたい、<br>
			フランス菓子を神戸という土地に根付かせたい、<br>という想いでお菓子を作っています。 <br>
			古くから外国の文化や食に親しみ、伝統を守りながらも、<br>
			新しいものを上手に取り入れて今の時代を見つめながらも、<br>
			その時々の動きに流されず、旬のもの、からだにやさしいものを、<br>基本の製法を踏まえて作っていきたいと考えています。
        </div>
        <div class="col-lg-6">
           <img class="image" src="https://demo.tcd-theme.com/tcd029/wp-content/uploads/2015/11/about04.jpg" alt="" title="" style="max-width: 100%;">
        </div>
    </div>
</div>

app/views/products/index.html.erb
<div class="row products">
	<div class="col-md-2 genre-form">
	<%= render 'products/genres-search', genres: @genres %>
	</div>
	<div class="col-md-10">
			<div class="row">
			  	<% if params[:genre_id] %>
			  		<h4 class="Menu"><%= @genre.genre_name %><%= @products.count %>件</h4>
			  	<% else %>
			    	<h4 class="Menu">MENU全<%= @products.count %>件</h4>
			    <% end %>
	    	</div>
	 		<% @products.each do |product| %>

		    	<div class="col-md-3">

		      	<%= link_to product_path(product) do %>
			      	<%= attachment_image_tag product, :image, :fill, 200, 200, fallback: "no-data.jpg", size:"200x200", class: "img-thumbnail" %>
			        <p class="price"><%= product.name.truncate(12, omission: '...') %></p>
	            <% end %>
		        <p class="price">
		            <% if product.status == false %>
			          売切れ
			      	<% else %>
			      	    <%= product.price %>円(+税)
			        <% end %>
			    </p>
		    </div>
		<% end %>
    </div>
</div>

app/views/products/search.html.erb
<h4 class="Menu">SEARCH　RESULT</h4>
<div class="row">
  <% if @products.present? %>
    <h2>products search for " <%= params[:search] %> "</h2>
      <% @products.each do |product| %>
	  <tr>
	    <div class="col-md-3">
	      <td>
	      	<%= link_to product_path(product) do %>
	      	<%= attachment_image_tag product, :image, :fill, 100, 100, fallback: "no-data.jpg", size:"100x100" %><br>
	        <%= product.name %>
	        <% end %>
		  </td><br>
	      <td>
	      	<% if product.status == false %>
	          売切れ
	      	<% else %>
	      	  <%= product.price %>円(+税)
	        <% end %>
	      </td>
	    </div>
	  </tr>
  	  <% end %>
  <% else %>
    <h2>products search for " <%= params[:search] %> "</h2>
      ・該当の商品はありません
<% end %>
</div>

app/views/products/show.html.erb
<div class="row products">
	<h4 class="Menu">MENU</h4>
	<div class="col-md-2 genre-form">
	    <%= render 'products/genres-search', genres: @genres %>
    </div>
	<div class="col-md-10">
	  <div class="row">
		<div class="col-md-4 item-image" >
		  <%= attachment_image_tag @product, :image, :fill, 300, 300, fallback: "no-data.jpg", size:"300x300" , class: "img-thumbnail"%>
		</div>
		<div class="col-md-1"></div>
		<div class="col-md-7">
		  <%= form_for(@cart_item , url: cart_items_path(product_id: @product), method: :post) do |f| %>
			<h3 class="price name"><%= @product.name %></h3>
			<p class="price"><%= @product.introduction %></p>
	        <p class="price"><%= @product.tax_price.to_s(:delimited) %>円 (税込)</p>
      		<% if @product.status == false %>
		       <p>売切れ</p>
		  	<% else %>
			<%= f.select :quantity, options_for_select((1..10).to_a) , include_blank: "個数選択", selected: 1 %>
            <%= f.hidden_field :product_id, value: @product.id %>
            <%= f.submit "カートに入れる", class: "btn btn-primary product-submit" %>
            <% end %>
		  <% end %>
	    </div>
	  </div>
	</div>
</div>

app/views/products/top.html.erb
<div id="container">
    <div id="theTarget">
        <div class="image1">
	      	<div class="main-visual-text" >
				<p>WELCOME NAGANOCAKE</p>
			</div>
        </div>
        <div class="image2">
      	    <div class="main-visual-text" >
			    <p>WELCOME NAGANOCAKE</p>
		    </div>
        </div>
        <div class="image3">
      	    <div class="main-visual-text" >
			    <p>WELCOME NAGANOCAKE</p>
		    </div>
        </div>
        <div class="image4">
      	    <div class="main-visual-text" >
			    <p>WELCOME NAGANOCAKE</p>
		    </div>
        </div>
        <div class="image5">
      	    <div class="main-visual-text" >
			    <p>WELCOME NAGANOCAKE</p>
		    </div>
        </div>
    </div>
</div>
<div class="row products" >
	<div class="top-text-box">
		<p>このサイトは、ケーキ販売のECサイトになります。会員でない方も商品の閲覧はできますが、購入には会員登録が必要になります。</p>
	</div>
	<h4 class="Menu">PICK UP MENU</h4>
	<div class="col-md-2 genre-form">
	    <%= render 'products/genres-search', genres: @genres %>
    </div>
    <div class="col-md-10">
	    <% @recommendation.each do |product| %>
		    <div class="col-md-3">
	            <div class="products-img"align="center">
					<%= link_to product_path(product) do %>
						<%= attachment_image_tag product, :image, :fill, 200, 200, fallback: "no-data.jpg", size:"200x200", class: "img-rounded" %>
						<p class="price top"><%= product.name.truncate(12, omission: '...') %></p>
				        <p class="price"><%= "#{product.tax_price}円"%></p>
				    <% end %>
				</div>
			</div>
	    <% end %>
    </div>
</div>
<div class="row readmore top">
	<p><%= link_to "Read more▶️", products_path %></p>
</div>

<div class="row">
	<div class="col-md-6">
		<h3 class="main-titles Menu">SPESIAL THANKS</h3>
		<p class="border-bottom"></p>
		<p class="main-text">
			数あるケーキショップの中から、ご閲覧いただきありがとうございます。<br>客様の体と心の健康を第一に考え、より自然な素材で添加物を極力使用せず、<br>
			そしてどこよりもお値打ちでご提供し、<br>全てのお客様に愛されるお菓子屋でありたい・・・。<br>
			それがの願いです。<br>
			私達はこの想いを大切に、お菓子づくりに取り組んでいます。
		</p>
    </div>
    <div class="col-lg-6">
    	<img class="product-image" src="https://demo.tcd-theme.com/tcd029/wp-content/uploads/2015/11/about01.jpg" alt="" title="" style="max-width: 100%;">
    </div>
</div>
<div class="row">
	<div class="col-lg-6">
    	<img class="product-image" src="https://demo.tcd-theme.com/tcd029/wp-content/uploads/2015/11/about02.jpg" alt="" title="" style="max-width: 100%;">
    </div>
	<div class="col-md-6">
		<h3 class="subtitles Menu">SHOP INFOMATION</h3>
		<p class="profile-text">
			卵や牛乳、水、果物など、お菓子に必要な素材を、<br>
			地元の契約農家や農場より直接仕入れ、<br>
			その生産地でお菓子づくりを行う素材本位の工場システムを、<br>「ファームファクトリー」と呼んでいます。<br>
			原材料を直接仕入れ、国内の自社工場で製造、<br>
			全国のお店へダイレクトに配送するという、問屋を通さないこの画期的な構想は、<br>
			当時の常識を覆す流通革命として昭和60年から始まりました。<br>
			現在では、農家との素材共同開発や、<br>生産農家が見える安全・安心なお菓子づくりへと広がっています。<br>
			おいしさとお値打ち価格、そして安全・安心が加わったNAGANOCAKEのお菓子。<br>
			これからもファームファクトリー構想を礎に、お客様へ笑顔をお届けいたします。
		</p>
	</div>
</div>
<div class="row">
	<div class="col-md-6">
		<h3 class="main-titles Menu">SAFETY</h3>
		<p class="border-bottom"></p>
		<p class="main-text">
			NAGANOCAKEは、お客様の心と体の健康を考え、添加物を極力使用しない商品や<br>
            糖質カット、アレルギー対応のお菓子づくりに取り組んでいます。<br>
            糖質が気になり食べたくても食べられない方のために、<br>
            食物繊維やマルチトール（還元麦芽糖）、ノンカロリー甘味料を使用したお菓子を完成させました。<br>
            手間をかけて素材おいしさを引き出す製法で、<br>
            添加物を使わない安全・安心なおいしいお菓子をお届けしています。
		</p>
    </div>
    <div class="col-lg-6">
    	<img class="product-image" src="https://demo.tcd-theme.com/tcd029/wp-content/uploads/2015/11/28.jpg" alt="" title="" style="max-width: 100%;">
    </div>
</div>
<h3 class="main-titles Menu">OFFICIAL ACCOUNT</h3>
<p class="border-bottom"></p>
<div class="contact-contents clearfix">
    <div class="contact-box">
      <div class="col-lg-4">
	    <p class="contact-subtitles">MAIL</p>
	    <p class="mail"><u>GUNDUM@WHITE.com</u></p>
	    <p class="contact-subtitles">Tell</p>
	    <p class="tell"><u>090-4894-94949</u></p>
	  </div>
    </div>
    <div class="contact-box">
      <div class="col-lg-4">
        <p class="contact-subtitles">SNS</p>
        <i class="fab fa-facebook-f" style="font-size: 30px;"></i>
        <i class="fab fa-twitter-square" style="font-size: 30px;"></i>
        <i class="fab fa-instagram" style="font-size: 30px;"></i>
      </div>
    </div>
    <div class="contact-box">
    	<div class="col-lg-4">
    		<p class="subtitles">GUNDUM TEAM <i class="fas fa-robot"></i></p>
			<p class="skills-info">マッキー、みやちゃん、さのっち、まえちゃん</p>
		</div>
	</div>
</div>